INSERT INTO DEPARTEMENT (id, libelle) VALUES(1,'Sous fifre')
INSERT INTO DEPARTEMENT (id, libelle) VALUES(2,'Chef de projet')
INSERT INTO DEPARTEMENT (id, libelle) VALUES(3,'Directeur Business Unit')
INSERT INTO DEPARTEMENT (id, libelle) VALUES(4,'Président Directeur Général')

INSERT INTO COLLABORATEUR (matricule, nom, prenom, departement_id, actif, nombanque, iban, bic) VALUES('M100', 'Dimper', 'Olivier', 4, true, 'SG', 'IBAN01', 'IBAN01')
INSERT INTO COLLABORATEUR (matricule, nom, prenom, departement_id, actif, nombanque, iban, bic) VALUES('M101', 'De Mauvieux', 'Tristan', 3, true, 'SG', 'IBAN02', 'IBAN02')
INSERT INTO COLLABORATEUR (matricule, nom, prenom, departement_id, actif, nombanque, iban, bic) VALUES('M102', 'Bourdaud', 'Valentin', 3, true, 'CA', 'IBAN03', 'IBAN03')
INSERT INTO COLLABORATEUR (matricule, nom, prenom, departement_id, actif, nombanque, iban, bic) VALUES('M103', 'Cayla', 'Pierre-Antoine', 2, true, 'CA', 'IBAN04', 'IBAN04')
INSERT INTO COLLABORATEUR (matricule, nom, prenom, departement_id, actif, nombanque, iban, bic) VALUES('M104', 'Le Marié', 'Valentin', 2, true, 'BNP', 'IBAN05', 'IBAN05')
INSERT INTO COLLABORATEUR (matricule, nom, prenom, departement_id, actif, nombanque, iban, bic) VALUES('M105', 'Lauret', 'Sony', 1, true, 'BNP', 'IBAN06', 'IBAN06')
INSERT INTO COLLABORATEUR (matricule, nom, prenom, departement_id, actif, nombanque, iban, bic) VALUES('M106', 'Vignoud', 'Sébastien', 1, true, 'POP', 'IBAN07', 'IBAN07')
INSERT INTO COLLABORATEUR (matricule, nom, prenom, departement_id, actif, nombanque, iban, bic) VALUES('M106', 'Merlin', 'Johnatan', 1, false, 'POP', 'IBAN08', 'IBAN08') 
